# Generated by Django 5.0.1 on 2024-02-12 16:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subnet',
            field=models.CharField(default='local_iVan', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='usuario/defaultUsuario.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
