# Generated by Django 5.0.1 on 2024-02-06 02:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SorteoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default=2, max_length=10)),
                ('activo', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('ganador', models.CharField(blank=True, max_length=40, null=True)),
                ('recarga', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('servicio', models.CharField(max_length=15)),
                ('eliminado', models.BooleanField(default=False)),
                ('mes', models.CharField(default=2, max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sync', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
