# Generated by Django 5.0.1 on 2024-02-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconexion',
            name='ip_online',
            field=models.CharField(blank=True, help_text='ip:port', max_length=30, null=True),
        ),
    ]
