# Generated by Django 5.0.1 on 2024-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='creator',
            field=models.CharField(default='0n3', max_length=20),
        ),
    ]
